[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_twitter = "DTpzL966JaPFA1VfoyF5CNdYkSoKPLDXqJErpuJvjcTK"

[programs.devnet]
solana_twitter = "DTpzL966JaPFA1VfoyF5CNdYkSoKPLDXqJErpuJvjcTK"

[programs.mainnet]
solana_twitter = "DTpzL966JaPFA1VfoyF5CNdYkSoKPLDXqJErpuJvjcTK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/vaibhav/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
